services:

  api:
    build: .
    environment:
      - PORT=1111

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"

  krakend:
    image: devopsfaith/krakend
    links:
      - "keycloak"
      - "api"
    command: run -d -c /etc/krakend/krakend.json
    ports:
      - "8000:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
